### ISSUE TITLE
Node engine compatibility

### ISSUE THREAD

**Issue by jaydp17** [edwellbrook/node-tvdb#77]
Is it possible to bring down the node engine version required from >= `v6.0.0` to something like `v4.x`?

I understand the urge to write cutting edge JS code, but a lot of people don't run cutting edge node.js versions.
Probably you can use [babel](https://babeljs.io) for this?

I want to use this lib in an [AWS Lambda](https://aws.amazon.com/lambda) function, and Lambda supports Node.js `v4.3.2`.

If you want I can help you out with babel

**Comment by edwellbrook** [comment]
Instead of introducing another dependency and potentially build step, I just removed the only blocking ES6 feature, which was default parameter values. Seems `v4.3.2` supports everything else we were using.

Just opened a PR to make it compatible and added tests against `v4.3.2` in Travis. If you're able to give the new branch (`node-4`) a test against on AWS Lambda and check it works for you, that'd be great. Let me know if it works 😄

Will merge and update on npm if everything works! Cheers.

**Comment by edwellbrook** [comment]
Merged and updated on npm version (`3.0.1`). Feel free to reopen if this is still a problem.

**Comment by jaydp17** [comment]
Really sorry, for the late reply, it's working!
Thanks a lot 👍
